const DEFAULT_BASE_URL = "https://ima.qq.com";
const ENTERPRISE_KNOWLEDGE_BASE_NAME = "企业办公本数据中心";
const SHARED_KNOWLEDGE_BASE_TYPE = "KBT_SHARED_KB";

module.exports = {
  DEFAULT_BASE_URL,
  ENTERPRISE_KNOWLEDGE_BASE_NAME,
  SHARED_KNOWLEDGE_BASE_TYPE,
};
